### ISSUE TITLE
Fogstream ревью

### ISSUE THREAD

**Issue by nikvst** [Sanchoyzer/web_app#1]
1. Задачка по БД. 
Фамилию, имя и отчечство нет смысла разность по отдельным таблицам.
С window есть подвох. Это json поле и если присмотреться, то видно, что это просто параметы некоторого окна и использоваться, оно скорее всего будет целиком. Поэтому тут можно просто воспользоваться типом json (если мы говорим о postgresql или других СУБД, поддерживающих такой тип данных). Даже если выносить эти данные в отдельную таблицу, то связь через связующую таблицу тоже лишняя, достаточно обойтись внешним ключом

2. `flake8 ничего полезного не дал, ибо у PyCharm неплохой встроенный
надзор за pep8 и всем остальным. isort немного навел марафет, но и без
этого было не так уж и плохо.`
Была просьба использовать один из перечисленных инструментов, т.к. они позволяют положить конфигурационный файл в репозиторий (.pylint.rc, .isort.cfg) и в дальнейшем все разработчики на проекте (если их несколько) будут придерживаться одного и того же стиля. 

В `test_app/test_forms/models.py`, к тому же, длина строк превышает 79 символов -_-

3. Для моделей verbose_name тоже лучше указывать.

4. https://github.com/Sanchoyzer/web_app/blob/master/test_app/test_forms/views.py#L74
У values_list есть аргумент flat и тогда queryset сразу отдаст список.
https://docs.djangoproject.com/en/2.1/ref/models/querysets/#values-list

5. В EmailLog можно было добавить чуть больше полезной информации.

6. Нет миграций
https://github.com/Sanchoyzer/web_app/tree/master/test_app/test_forms/migrations

7. Под асинхронными запросами имелось ввиду не только использование тредов на сервере для отправки email, но и самый простой ajax на клиенте.

8. Такой вложенности лучше избегать
https://github.com/Sanchoyzer/web_app/blob/master/test_app/test_vk/views.py#L17

Как-то так
```
vk_user = None
if token is not None:
    vk_user = vku.VkUserInfo.get_obj(request.session.get(COOKIE_USER), token)

if vk_user is not None:
```

9. https://github.com/Sanchoyzer/web_app/blob/master/test_app/test_vk/views.py#L22
Такое сейчас стараются писать через list comprehension
`vk_friends = [vku.VkUserInfo.get_obj(friend_id, token) for friend_id in friends_list]`
Считается, что так очевиднее, чем использовать map и filter

В целом тестовое хорошее, молодец.

**Comment by Sanchoyzer** [comment]
1.
> Фамилию, имя и отчечство нет смысла разность по отдельным таблицам.

Тут такой смысл: фамилии уникальны, а вот справочник имен и отчеств сделать несложно. И чтобы человек, заводя пользователя, не опечатался, мы как раз страхуемся проверкой через справочник.

> Поэтому тут можно просто воспользоваться типом json

Я действовал в рамках стандарта, ибо не столь специфичная задачка

> С window есть подвох. Это json поле и если присмотреться, то видно, что это просто параметы некоторого окна и использоваться, оно скорее всего будет целиком.

Я исходил из того, что вполне возможен кейс, когда нужна будет статистика по средней длине-ширине окна "клиента", чтобы, например, соответствующе проектировать GUI.

> Даже если выносить эти данные в отдельную таблицу, то связь через связующую таблицу тоже лишняя, достаточно обойтись внешним ключом

Полагал, что таблица "работников", как и таблица "окон" -- это вспомогательные части чего-то главного. поэтому у меня та "вспомогательная таблица" как раз планировалась самой главной с внешними ключами к тем двум :) Причем, в моей схеме "окно" и "пользователь" не коррелируют. Иначе я бы так и сделал у "пользователя" ссылку на "окно".

2. 
> В test_app/test_forms/models.py, к тому же, длина строк превышает 79 символов

Я поклонник 120. В современные экраны классические 80 входят раза 3 :)

3.
> Для моделей verbose_name тоже лучше указывать.

Но у меня же указано https://github.com/Sanchoyzer/web_app/blob/master/test_app/test_forms/models.py#L5 , или я неверно понял? Или речь о verbose_name_plural?

4. 
> У values_list есть аргумент flat и тогда queryset сразу отдаст список.

О, вот это клевая штука

5. 
> В EmailLog можно было добавить чуть больше полезной информации.

Честно говоря, не придумал, что еще можно. Ну разве что дату

6.
> Нет миграций

До недавнего времени полагал, что миграции являются служебными файлами, поэтому их комитить не надо. Дескать, программист делает migrate у себя, а на рабочем будет свой запуск migrate, и начальные состояния могут не совпадать.

7. 
> Под асинхронными запросами имелось ввиду не только использование тредов на сервере для отправки email, но и самый простой ajax на клиенте.

Я в js не очень, тем паче -- в ajax, а времени вникать уже не было: сроки. Поэтому, выбирая, какая из операций более тяжелая: отправка запроса на сервер или выполнение серверной логики, я выбрал тредить сервер ;) Но согласен, что ajax бы не помешал.

8. 
> Такой вложенности лучше избегать

Согласен

9. 
> Такое сейчас стараются писать через list comprehension

Тоже согласен

**Comment by nikvst** [comment]
1. ок, логику понял
2. поэтому и следует в проект класть pylint.rc, где указано, что длина строки < 120 символов =)
3. речь о verbose_name для самой модели, то что выводится в админке. https://docs.djangoproject.com/en/2.1/ref/models/options/#verbose-name
```
class SomeModel(models.Model):

    class Meta:
        verbose_name = "некоторая модель"
        verbose_name_plural = "некоторые модели"
```
5. email_subject и email_msg, например.

6. Это сработает только для первичного запуска проекта. Но если где-то наше приложение уже развернуто и в БД имеются какие-то данные, то при обновлении нам как раз и нужны миграции, которые аккуратно приведут нашу базу к актуальному состоянию.
Может быть эта статья расскажет лучше https://habr.com/post/121265/
